<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="8" skipped="0" failures="1" errors="0" timestamp="2019-12-27T19:39:55" hostname="DESKTOP-78D8MC1" time="0.034">
  <properties/>
  <testcase name="testSolutionUsingOnlyWhiteSpace" classname="Tests" time="0.008"/>
  <testcase name="testSolutionUsingNullPhrase" classname="Tests" time="0.001"/>
  <testcase name="testSolutionUsingPhraseWithHyphenatedWord" classname="Tests" time="0.002"/>
  <testcase name="testSolutionUsingPhraseWithAcronym" classname="Tests" time="0.001"/>
  <testcase name="testSolutionUsingPhraseWithExcessWhiteSpace" classname="Tests" time="0.004">
    <failure message="java.lang.StringIndexOutOfBoundsException: String index out of range: 0" type="java.lang.StringIndexOutOfBoundsException">java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at Task.createAcronymFromPhrase(Task.java:27)
	at Tests.testSolutionUsingPhraseWithExcessWhiteSpace(Tests.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="testSolutionUsingEmptyPhrase" classname="Tests" time="0.006"/>
  <testcase name="testSolutionUsingSimplePhrase" classname="Tests" time="0.002"/>
  <testcase name="testSolutionUsingPhraseWithPunctuation" classname="Tests" time="0.008"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
