<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="5" skipped="0" failures="1" errors="0" timestamp="2019-12-30T21:11:11" hostname="MSI" time="0.025">
  <properties/>
  <testcase name="testSolutionWithNegativeFrequency" classname="Tests" time="0.016"/>
  <testcase name="testSolutionWithValidValues" classname="Tests" time="0.006">
    <failure message="java.lang.AssertionError: expected:&lt;1161.62&gt; but was:&lt;1001.5&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;1161.62&gt; but was:&lt;1001.5&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at Tests.testSolutionWithValidValues(Tests.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="testSolutionWithNegativeRate" classname="Tests" time="0.001"/>
  <testcase name="testSolutionWithNegativeTime" classname="Tests" time="0.001"/>
  <testcase name="testSolutionWithNegativePrincipal" classname="Tests" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
