<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="7" skipped="0" failures="4" errors="0" timestamp="2019-12-23T18:20:54" hostname="DESKTOP-R0R2739" time="0.032">
  <properties/>
  <testcase name="testSolutionUsingStringWithCapitalizedLetter" classname="Tests" time="0.022">
    <failure message="org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[nemaR]&gt; but was:&lt;[Ramen]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[nemaR]&gt; but was:&lt;[Ramen]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at Tests.testSolutionUsingStringWithCapitalizedLetter(Tests.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="testSolutionUsingPalindrome" classname="Tests" time="0.003"/>
  <testcase name="testSolutionUsingNullString" classname="Tests" time="0.001"/>
  <testcase name="testSolutionUsingStringWithNewLines" classname="Tests" time="0.001">
    <failure message="org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[654&#10;fed&#10;321&#10;cba]&gt; but was:&lt;[abc&#10;123&#10;def&#10;456]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[654
fed
321
cba]&gt; but was:&lt;[abc
123
def
456]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at Tests.testSolutionUsingStringWithNewLines(Tests.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="testSolutionUsingEmptyString" classname="Tests" time="0.0"/>
  <testcase name="testSolutionUsingSimpleString" classname="Tests" time="0.002">
    <failure message="org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[tobor]&gt; but was:&lt;[robot]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[tobor]&gt; but was:&lt;[robot]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at Tests.testSolutionUsingSimpleString(Tests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="testSolutionUsingStringWithPunctuationAndSpaces" classname="Tests" time="0.001">
    <failure message="org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[!yrgnuh m'I]&gt; but was:&lt;[I'm hungry!]&gt;" type="org.junit.ComparisonFailure">org.junit.ComparisonFailure: The method is expected to reverse the provided String argument. expected:&lt;[!yrgnuh m'I]&gt; but was:&lt;[I'm hungry!]&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at Tests.testSolutionUsingStringWithPunctuationAndSpaces(Tests.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <system-out><![CDATA[Ramen
racecar
abc
123
def
456
robot
I'm hungry!
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
