<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="EmployeeTest" tests="5" skipped="0" failures="1" errors="0" timestamp="2019-12-31T01:49:25" hostname="MSI" time="0.007">
  <properties/>
  <testcase name="testToEnsureThatEmployeeCannotBeInstantiatedWithNegativeId" classname="EmployeeTest" time="0.0"/>
  <testcase name="testToEnsureThatEmployeeCannotBeInstantiatedWithNegativeSalary" classname="EmployeeTest" time="0.001"/>
  <testcase name="testIfEmployeeIsProperPojo" classname="EmployeeTest" time="0.003">
    <failure message="java.lang.AssertionError: Missing required method. Class does not properly implement POJO design pattern." type="java.lang.AssertionError">java.lang.AssertionError: Missing required method. Class does not properly implement POJO design pattern.
	at org.junit.Assert.fail(Assert.java:88)
	at EmployeeTest.testIfEmployeeIsProperPojo(EmployeeTest.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="testToEnsureThatSalaryCannotBeSetToNegativeNumber" classname="EmployeeTest" time="0.001"/>
  <testcase name="testToEnsureThatIdCannotBeSetToNegativeNumber" classname="EmployeeTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
