<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Tests" tests="7" skipped="0" failures="0" errors="0" timestamp="2019-12-23T21:00:44" hostname="DESKTOP-R0R2739" time="0.06">
  <properties/>
  <testcase name="testCountWordsWithEmptyStringArray" classname="Tests" time="0.009"/>
  <testcase name="testExtractTextWithExistingFileContainingText" classname="Tests" time="0.021"/>
  <testcase name="testCountWordsWithValidStringArray" classname="Tests" time="0.001"/>
  <testcase name="testExtractTextWithNullFile" classname="Tests" time="0.001"/>
  <testcase name="testExtractTextWithMissingFile" classname="Tests" time="0.02"/>
  <testcase name="testCountWordsWithNullStringArray" classname="Tests" time="0.0"/>
  <testcase name="testExtractTextWithExistingEmptyFile" classname="Tests" time="0.004"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[java.io.FileNotFoundException: resources\missing.txt (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at Task.extractTextFromFile(Task.java:13)
	at Tests.testExtractTextWithMissingFile(Tests.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
]]></system-err>
</testsuite>
